### ISSUE TITLE
Wont get past recovery screen

### ISSUE THREAD

**Issue by Youraveragejoshhutcherson** [MercuryWorkshop/RecoMod#47] opened 2023-12-08 02:37 UTC
It says "the device owner requires this device with chrome os verification turned on" did this get patched?
![17020030357466237905412664320567](https://github.com/MercuryWorkshop/RecoMod/assets/153250741/97b09f36-23c5-4719-b733-65073897cd24)
(And no, i didnt do anything wrong)

**Comment by c0des1ay3r** [comment] 2023-12-19 14:33
@CoolElectronics

**Comment by velzie** [comment] 2023-12-19 15:18
duplicate of #6 and a few others please read before making a report you have to use sh1mmer first

**Closed as not planned by velzie** 2023-12-19 15:18 UTC

**Comment by c0des1ay3r** [comment] 2023-12-19 18:08
@CoolElectronics Tried that, it still errors out with the same message.

**Comment by velzie** [comment] 2023-12-19 18:21
then you did it wrong. everything here still works

**Comment by c0des1ay3r** [comment] 2023-12-19 18:44
Step 1. Unenroll w/ Sh1mmer (ignore error)
Step 2. Get to dev mode blocked screen
Step 3. Esc + Refresh + Power back into Recovery mode
Step 4. Insert USB and start spamming E
Explain what I missed here.
